title: "Luis Valente"
description: "Engineering • Projects • Writings"
url: "https://lc120109.github.io"
baseurl: ""  # for user/organization site; leave blank

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-remote-theme
  # - jekyll-paginate       # enable only if needed
  # - jekyll-gist           # enable only if posts use {% gist %}

remote_theme: poole/hyde

# Optional pagination config (only if you enabled jekyll-paginate)
# paginate: 5
# paginate_path: "/page:num/"
